[package]
authors = ["tillarnold <throwable42@gmail.com>"]
name = "left-pad-io"
version = "0.0.2"
description = "Rest client for left-pad.io"
license = "MIT"
repository = "https://github.com/tillarnold/left-pad-io"

[dependencies]
hyper = "0.9.10"
quick-error = "1.0.0"
rustc-serialize = "0.3.18"
